In [1]:
import numpy as np #Deals with array and matrix

# Methods to create Array in numpy

In [2]:
l = [1,2,3,4]
np.array(l) #Converting in array and always create a new copy if l is array

array([1, 2, 3, 4])

In [3]:
arr = np.array(l) #n-dimensional array
type(arr)

numpy.ndarray

In [4]:
np.array([[1,2],[3,4]]) #2-dimensional

array([[1, 2],
       [3, 4]])

In [5]:
# Can take list type input like tuple etc
np.asarray(l) #Converting in array and does nt create a new copy if l is array

array([1, 2, 3, 4])

In [6]:
a = [1,2,3]

In [7]:
np.asanyarray(a) #creates a new array

array([1, 2, 3])

In [8]:
b = np.matrix(l) #default 2-dimensional and subset of array and should be avoided

In [150]:
type(b)

numpy.matrix

In [10]:
np.asanyarray(b) #Does not convert into array as it is already a form of array

matrix([[1, 2, 3, 4]])

In [11]:
a = np.array(l)

In [12]:
a

array([1, 2, 3, 4])

In [14]:
c = a # c and a are both referecing to same object .Also know as shallow copy

In [15]:
c

array([1, 2, 3, 4])

In [16]:
a

array([1, 2, 3, 4])

In [17]:
c[0] = 100

In [18]:
c

array([100,   2,   3,   4])

array([100,   2,   3,   4])

In [22]:
d = np.copy(a) #Referencing to different object. Also know as Deep Copy

In [23]:
d

array([100,   2,   3,   4])

In [24]:
a

array([100,   2,   3,   4])

In [25]:
a[1] = 400

In [26]:
a

array([100, 400,   3,   4])

In [27]:
d

array([100,   2,   3,   4])

In [28]:

np.fromfunction(lambda i, j : i==j, (2,2)) # function to create array using x and y indexes

array([[ True, False],
       [False,  True]])

In [29]:
np.fromfunction(lambda i, j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [32]:
np.fromfunction(lambda i, j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [36]:
iterable = (i*i for i in range(5))

In [37]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [38]:
np.fromstring("234 234", sep = " ")

array([234., 234.])

In [39]:
np.fromstring("2,3", sep = ",")

array([2., 3.])

# Data types in numpy

In [41]:
l = [2,3,4,5,6]

In [42]:
arr = np.array(l)

In [43]:
arr

array([2, 3, 4, 5, 6])

In [48]:
arr.ndim #Tell dimensional of array

1

In [45]:
arr2 = np.array([[1,2], [3,4]])

In [46]:
arr2

array([[1, 2],
       [3, 4]])

In [47]:
arr2.ndim

2

In [51]:
arr.size

5

In [52]:
arr2.size

4

In [53]:
arr.shape

(5,)

In [54]:
arr2.shape

(2, 2)

In [55]:
arr.dtype

dtype('int32')

In [56]:
arr2.dtype

dtype('int32')

In [59]:
arr3 = np.array([(1.4,45,45),(23,45,66)])

In [61]:
arr3

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [62]:
arr3.dtype


dtype('float64')

In [63]:
range(5)

range(0, 5)

In [64]:
list(range(5))

[0, 1, 2, 3, 4]

In [65]:
list(range(0.5,5))

TypeError: 'float' object cannot be interpreted as an integer

In [66]:
np.arange(2.3,5.6) #Able to take float

array([2.3, 3.3, 4.3, 5.3])

In [67]:
np.arange(2.3,4.5,0.2)

array([2.3, 2.5, 2.7, 2.9, 3.1, 3.3, 3.5, 3.7, 3.9, 4.1, 4.3])

In [68]:
list(np.arange(2.3,4.5,0.2))

[2.3,
 2.5,
 2.7,
 2.9000000000000004,
 3.1000000000000005,
 3.3000000000000007,
 3.500000000000001,
 3.700000000000001,
 3.9000000000000012,
 4.100000000000001,
 4.300000000000002]

In [69]:
np.linspace(1,5,10) #Produce 10 data within a limit

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [70]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [71]:
np.zeros((3,4)) #dimension given

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [72]:
np.zeros((3,4,2)) # 3dimensional array

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [73]:
np.zeros((2,3,4,5)) #3 dimensional array

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [74]:
np.ones(4)

array([1., 1., 1., 1.])

In [75]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [77]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [78]:
on = np.ones((2,3,2))

In [79]:
on *4


array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [80]:
on + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [81]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [82]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [83]:
np.empty((3,6)) #create array with random values

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [84]:
np.eye(4) # Identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [86]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [87]:
np.logspace(2,5,5) #creates log

array([   100.        ,    562.34132519,   3162.27766017,  17782.79410039,
       100000.        ])

In [88]:
np.logspace(2,5,5, base = 2) #creates log

array([ 4.        ,  6.72717132, 11.3137085 , 19.02731384, 32.        ])

In [89]:
# Generate data

In [90]:
np.random.randn(3,4)

array([[ 0.50746992,  1.70037352, -0.6068595 ,  0.52457266],
       [ 0.44751904,  0.29117379, -1.50825832, -1.32963568],
       [ 0.13953197,  0.08094406,  0.00479486,  0.24017741]])

In [92]:
arr = np.random.randn(3,4) # Data mean = 0 and std = 1

In [93]:
import pandas as pd
pd.DataFrame(arr)

0         1         2         3
0 -0.933252  0.866924  0.284041 -1.345803
1 -0.630442  0.573203  0.490340 -0.335429
2  0.513992  1.082106  0.234158 -0.338659

In [94]:
np.random.rand(3,4) # produces number between 0 and 1

array([[0.90450811, 0.40584853, 0.86122176, 0.43305101],
       [0.51295072, 0.46803237, 0.45347627, 0.84075568],
       [0.27012201, 0.25302866, 0.02533038, 0.44103641]])

In [95]:
np.random.randint(1,110,(3,4)) #Produces integer

array([[ 88,  44,  65,  35],
       [  3,   5,  15,  95],
       [105,  20, 106,  96]])

In [96]:
pd.DataFrame(np.random.randint(1,110,(3,4)))

0   1   2   3
0  69  62  53  31
1  83  26   9  62
2  60  68  42  98

In [97]:
pd.DataFrame(np.random.randint(1,110,(3,4))).to_csv("test2.csv")

In [98]:
arr = np.random.rand(3,4)

In [99]:
arr

array([[0.22242953, 0.42887871, 0.35431123, 0.65576842],
       [0.61641949, 0.03149257, 0.39210625, 0.60949654],
       [0.56458181, 0.01524837, 0.47309342, 0.34823161]])

In [100]:
arr.reshape(6,2) #Rearranging shape

array([[0.22242953, 0.42887871],
       [0.35431123, 0.65576842],
       [0.61641949, 0.03149257],
       [0.39210625, 0.60949654],
       [0.56458181, 0.01524837],
       [0.47309342, 0.34823161]])

In [101]:
arr.reshape(6,-1) #Takes 2 automatically

array([[0.22242953, 0.42887871],
       [0.35431123, 0.65576842],
       [0.61641949, 0.03149257],
       [0.39210625, 0.60949654],
       [0.56458181, 0.01524837],
       [0.47309342, 0.34823161]])

In [102]:
arr1 = arr.reshape(6,-1)

In [103]:
arr1[1][1]

0.6557684162114712

In [104]:
arr1[1]

array([0.35431123, 0.65576842])

In [106]:
arr1[1][1]

0.6557684162114712

In [107]:
arr1[1:4]

array([[0.35431123, 0.65576842],
       [0.61641949, 0.03149257],
       [0.39210625, 0.60949654]])

In [108]:
arr1[1:4][1]

array([0.61641949, 0.03149257])

In [109]:
np.random.randint(1,100,(5,5))

array([[10,  9,  5, 73,  1],
       [83, 33, 14, 64, 24],
       [31, 16, 63, 29, 45],
       [36, 29, 28, 75, 56],
       [17, 99, 16, 74,  4]])

In [110]:
arr = np.random.randint(1,100,(5,5))

In [111]:
arr

array([[34, 75, 83, 25,  2],
       [92, 34, 28, 90, 98],
       [66, 33, 80, 73, 39],
       [58, 72, 66, 18, 10],
       [85, 22, 43, 55, 64]])

In [112]:
arr >50

array([[False,  True,  True, False, False],
       [ True, False, False,  True,  True],
       [ True, False,  True,  True, False],
       [ True,  True,  True, False, False],
       [ True, False, False,  True,  True]])

In [113]:
arr[arr > 50]

array([75, 83, 92, 90, 98, 66, 80, 73, 58, 72, 66, 85, 55, 64])

In [115]:
arr[2:4,[1,2]]

array([[33, 80],
       [72, 66]])

In [116]:
arr[0][0]

34

In [117]:
arr[0][0] = 5000

In [118]:
arr

array([[5000,   75,   83,   25,    2],
       [  92,   34,   28,   90,   98],
       [  66,   33,   80,   73,   39],
       [  58,   72,   66,   18,   10],
       [  85,   22,   43,   55,   64]])

In [120]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [121]:
arr1

array([[1, 1, 2],
       [2, 2, 2],
       [2, 2, 1]])

In [122]:
arr2

array([[2, 2, 2],
       [1, 2, 1],
       [1, 1, 1]])

In [123]:
arr1 + arr2

array([[3, 3, 4],
       [3, 4, 3],
       [3, 3, 2]])

In [124]:
arr1 - arr2

array([[-1, -1,  0],
       [ 1,  0,  1],
       [ 1,  1,  0]])

In [125]:
arr1 / arr2

array([[0.5, 0.5, 1. ],
       [2. , 1. , 2. ],
       [2. , 2. , 1. ]])

In [126]:
arr1 * arr2 # Not matrix multiplication

array([[2, 2, 4],
       [2, 4, 2],
       [2, 2, 1]])

In [127]:
arr1@arr2 # matrix multiplication

array([[ 5,  6,  5],
       [ 8, 10,  8],
       [ 7,  9,  7]])

In [128]:
arr1/0

C:\Users\dhruv\AppData\Local\Temp\ipykernel_17036\1510032488.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [129]:
arr1 + 100

array([[101, 101, 102],
       [102, 102, 102],
       [102, 102, 101]])

In [130]:
arr1**2

array([[1, 1, 4],
       [4, 4, 4],
       [4, 4, 1]])

In [131]:
# Broadcasting in numpy

In [132]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [133]:
arr = np.zeros((4,4))

In [134]:
row = np.array([1,2,3,4])

In [135]:
row

array([1, 2, 3, 4])

In [136]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [137]:
arr + row #row wise addition i.e broadcasting

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [140]:
column = np.array([[1,2,3,4]]).transpose()

In [141]:
column

array([[1],
       [2],
       [3],
       [4]])

In [142]:
column + arr # Broadcasting column vice

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [143]:
np.random.randint(1,4, (3,4))

array([[2, 1, 3, 2],
       [3, 1, 1, 3],
       [2, 3, 1, 1]])

In [144]:
arr1 = np.random.randint(1,4, (3,4))

In [145]:
arr1

array([[3, 2, 2, 3],
       [3, 2, 2, 2],
       [2, 2, 3, 3]])

In [146]:
np.sqrt(arr1)

array([[1.73205081, 1.41421356, 1.41421356, 1.73205081],
       [1.73205081, 1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.73205081, 1.73205081]])

In [147]:
np.exp(arr1)

array([[20.08553692,  7.3890561 ,  7.3890561 , 20.08553692],
       [20.08553692,  7.3890561 ,  7.3890561 ,  7.3890561 ],
       [ 7.3890561 ,  7.3890561 , 20.08553692, 20.08553692]])

In [148]:
np.log10(arr1)

array([[0.47712125, 0.30103   , 0.30103   , 0.47712125],
       [0.47712125, 0.30103   , 0.30103   , 0.30103   ],
       [0.30103   , 0.30103   , 0.47712125, 0.47712125]])