In [1]:
# Numpy Array Manipulation

In [2]:
import numpy as np

In [4]:
arr = np.random.randint(1,10,(3,4))

In [5]:
arr

array([[6, 4, 5, 2],
       [2, 7, 5, 5],
       [9, 4, 6, 7]])

In [6]:
arr.reshape(2,6)

array([[6, 4, 5, 2, 2, 7],
       [5, 5, 9, 4, 6, 7]])

In [7]:
arr.reshape(2,7)

ValueError: cannot reshape array of size 12 into shape (2,7)

In [10]:
arr.reshape(2,-1)

array([[6, 4, 5, 2, 2, 7],
       [5, 5, 9, 4, 6, 7]])

In [11]:
arr

array([[6, 4, 5, 2],
       [2, 7, 5, 5],
       [9, 4, 6, 7]])

In [12]:
arr.flatten()

array([6, 4, 5, 2, 2, 7, 5, 5, 9, 4, 6, 7])

In [13]:
arr

array([[6, 4, 5, 2],
       [2, 7, 5, 5],
       [9, 4, 6, 7]])

In [14]:
arr1 = np.array([1,2,3,4,3])

In [16]:
arr1.ndim

1

In [17]:
np.expand_dims(arr1, axis=1) # Changes dimension from 1 to 2

array([[1],
       [2],
       [3],
       [4],
       [3]])

In [18]:
np.expand_dims(arr1, axis=0)

array([[1, 2, 3, 4, 3]])

In [19]:
arr

array([[6, 4, 5, 2],
       [2, 7, 5, 5],
       [9, 4, 6, 7]])

In [20]:
np.squeeze(arr)

array([[6, 4, 5, 2],
       [2, 7, 5, 5],
       [9, 4, 6, 7]])

In [22]:
arr =np.array([[1],[2],[3]])

In [23]:
arr

array([[1],
       [2],
       [3]])

In [25]:
np.squeeze(arr) #Squeeze elements

array([1, 2, 3])

In [26]:
arr1

array([1, 2, 3, 4, 3])

In [27]:
np.repeat(arr1,3) #Repeats elements 3 times

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 3, 3, 3])

In [29]:
np.roll(arr1, 2) #It shifts data by 2 places

array([4, 3, 1, 2, 3])

In [30]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 3]])

In [31]:
# Numpy Binary Operations

In [32]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [33]:
arr1

array([[7, 7, 3, 9],
       [2, 1, 8, 5],
       [9, 9, 5, 5]])

In [34]:
arr2

array([[3, 2, 8, 3],
       [6, 3, 4, 6],
       [5, 2, 7, 1]])

In [35]:
arr1 + arr2

array([[10,  9, 11, 12],
       [ 8,  4, 12, 11],
       [14, 11, 12,  6]])

In [36]:
arr1 * arr2

array([[21, 14, 24, 27],
       [12,  3, 32, 30],
       [45, 18, 35,  5]])

In [37]:
arr1 - arr2

array([[ 4,  5, -5,  6],
       [-4, -2,  4, -1],
       [ 4,  7, -2,  4]])

In [38]:
arr1 % arr2

array([[1, 1, 3, 0],
       [2, 1, 0, 5],
       [4, 1, 5, 0]])

In [39]:
arr1 & arr2

array([[3, 2, 0, 1],
       [2, 1, 0, 4],
       [1, 0, 5, 1]])

In [41]:
~arr1

array([[ -8,  -8,  -4, -10],
       [ -3,  -2,  -9,  -6],
       [-10, -10,  -6,  -6]])

In [42]:
 arr1 | arr2

array([[ 7,  7, 11, 11],
       [ 6,  3, 12,  7],
       [13, 11,  7,  5]])

In [43]:
arr1 > arr2

array([[ True,  True, False,  True],
       [False, False,  True, False],
       [ True,  True, False,  True]])

In [44]:
# Numpy String Function

In [45]:
np.array(["Dhruv","Maheshwari"])

array(['Dhruv', 'Maheshwari'], dtype='<U10')

In [46]:
arr = np.array(["Dhruv","Maheshwari"])

In [47]:
np.char.upper(arr)

array(['DHRUV', 'MAHESHWARI'], dtype='<U10')

In [48]:
np.char.lower(arr)

array(['dhruv', 'maheshwari'], dtype='<U10')

In [49]:
np.char.title(arr)

array(['Dhruv', 'Maheshwari'], dtype='<U10')

In [50]:
np.char.capitalize(arr)

array(['Dhruv', 'Maheshwari'], dtype='<U10')

In [51]:
# Numpy Mathematical Fucntions

In [52]:
arr1

array([[7, 7, 3, 9],
       [2, 1, 8, 5],
       [9, 9, 5, 5]])

In [53]:
np.sin(arr1)

array([[ 0.6569866 ,  0.6569866 ,  0.14112001,  0.41211849],
       [ 0.90929743,  0.84147098,  0.98935825, -0.95892427],
       [ 0.41211849,  0.41211849, -0.95892427, -0.95892427]])

In [54]:
np.cos(arr1)

array([[ 0.75390225,  0.75390225, -0.9899925 , -0.91113026],
       [-0.41614684,  0.54030231, -0.14550003,  0.28366219],
       [-0.91113026, -0.91113026,  0.28366219,  0.28366219]])

In [55]:
np.tan(arr1)

array([[ 0.87144798,  0.87144798, -0.14254654, -0.45231566],
       [-2.18503986,  1.55740772, -6.79971146, -3.38051501],
       [-0.45231566, -0.45231566, -3.38051501, -3.38051501]])

In [57]:
np.log10(arr1)

array([[0.84509804, 0.84509804, 0.47712125, 0.95424251],
       [0.30103   , 0.        , 0.90308999, 0.69897   ],
       [0.95424251, 0.95424251, 0.69897   , 0.69897   ]])

In [58]:
np.exp(arr1)

array([[1.09663316e+03, 1.09663316e+03, 2.00855369e+01, 8.10308393e+03],
       [7.38905610e+00, 2.71828183e+00, 2.98095799e+03, 1.48413159e+02],
       [8.10308393e+03, 8.10308393e+03, 1.48413159e+02, 1.48413159e+02]])

In [59]:
np.sqrt(arr1)

array([[2.64575131, 2.64575131, 1.73205081, 3.        ],
       [1.41421356, 1.        , 2.82842712, 2.23606798],
       [3.        , 3.        , 2.23606798, 2.23606798]])

In [60]:
np.power(arr1, 2)

array([[49, 49,  9, 81],
       [ 4,  1, 64, 25],
       [81, 81, 25, 25]], dtype=int32)

In [61]:
np.mean(arr1)

5.833333333333333

In [64]:
np.median(arr1)

6.0

In [65]:
np.std(arr1)

2.6718699236469

In [66]:
np.var(arr1)

7.13888888888889

In [67]:
np.min(arr1)

1

In [68]:
np.max(arr1)

9