In [1]:
# Sort , Search and counting Function

In [2]:
import numpy as np

In [3]:
np.array([4,5,3,5,24,3,222,111])

array([  4,   5,   3,   5,  24,   3, 222, 111])

In [4]:
arr = np.array([4,5,3,5,24,3,222,111])

In [5]:
np.sort(arr)

array([  3,   3,   4,   5,   5,  24, 111, 222])

In [6]:
np.searchsorted(arr,34) #Tells the location for the correct insertion

6

In [7]:
arr1 = np.array([0,345,343,0,1,2343,0,0,0])

In [8]:
np.count_nonzero(arr1) #Tell count of non-zero data

4

In [9]:
arr

array([  4,   5,   3,   5,  24,   3, 222, 111])

In [10]:
np.where(arr > 6) #gives the index where condition meets

(array([4, 6, 7], dtype=int64),)

In [11]:
np.extract(arr > 6, arr) #Give array element

array([ 24, 222, 111])

In [12]:
# Byte swapping

In [13]:
arr.byteswap() #gives bytes

array([  67108864,   83886080,   50331648,   83886080,  402653184,
         50331648, -570425344, 1862270976])

In [14]:
arr

array([  4,   5,   3,   5,  24,   3, 222, 111])

In [15]:
a = np.copy(arr) #Deep Copy - Two copies

In [16]:
a

array([  4,   5,   3,   5,  24,   3, 222, 111])

In [17]:
b = arr.view() #Shallow copy- One copy

In [18]:
b[0] = 777

In [19]:
b

array([777,   5,   3,   5,  24,   3, 222, 111])

In [20]:
arr

array([777,   5,   3,   5,  24,   3, 222, 111])

In [21]:
# Numpy matrix library

In [22]:
import numpy.matlib as nm

In [24]:
nm.zeros(5) #generates matrix

matrix([[0., 0., 0., 0., 0.]])

In [26]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [28]:
# Linear Algebra

In [30]:
arr1 = np.random.randint([[2,3], [4,5]])
arr2 = np.random.randint([[5,3], [2,5]])

In [31]:
arr1

array([[0, 0],
       [0, 0]])

In [32]:
arr2

array([[1, 2],
       [0, 0]])

In [33]:
np.dot(arr1,arr2)

array([[0, 0],
       [0, 0]])

In [34]:
arr1@arr2

array([[0, 0],
       [0, 0]])